### ISSUE TITLE
Build is not passing

### ISSUE THREAD

**Issue by UnioDex** [dadus33/ChatItem#10]
Some of the repos are dead and build is not passing. Also where is ChatItemAPI class?

**Comment by sarhatabaot** [comment]
ChatAPI is an interface. I recreated it in [my fork](https://github.com/sarhatabaot/ChatItem/tree/dev).

**Comment by dadus33** [comment]
Hey @UnioDex , thanks for pointing it out. Unfortunately I found myself neglecting this project lately due to lack of time. As @sarhatabaot mentioned, ChatItemAPI is an interface and was part of another artifact published on a repo of a friend which is sadly no longer available. For now, the quick and dirty fix would be just adding the interface in the main artifact. That will change however as soon as I get more time to rewrite all this properly.
